ifeq ($(PREFIX),)
    PREFIX := /usr/local
endif

install:
	sudo cp git_pull_push.sh /usr/local/bin/git_pull_push
	sudo chmod +x /usr/local/bin/git_pull_push
	sudo cp update_system.sh /usr/local/bin/update_system
	sudo chmod +x /usr/local/bin/update_system