


P01=program1
P02=program2


EXECS= \
       $(P01) \
       $(P02) \


all:	seealso $(EXECS)

.phony: clean all seealso

clean: seealso
	rm -f ${EXECS}


seealso:
	@echo "======================="
	@echo "yeet"
	@echo "======================="
