# REV01 Mon Oct  7 13:53:38 WIB 2019
# START Mon Oct  7 13:40:47 WIB 2019

CC=gcc

P00=simpleRead
P01=simpleWriteX
P02=pipe1
P03=pipe2


EXECS= \
   $(P00) \
   $(P01) \
   $(P02) \
   $(P03) \


all:	$(EXECS)

.phony: clean all

clean:
	rm -f ${EXECS}

