install:
	mkdir -p ~/bin/
	cp upgrade.sh ~/bin/upgrade
	chmod 755 ~/bin/upgrade
	mkdir -p ~/bin/
	cp pullpush.sh ~/bin/pullpush
	chmod 755 ~/bin/upgrade
	mkdir -p ~/bin/
	cp cleanrepo.sh ~/bin/cleanrepo
	chmod 755 ~/bin/cleanrepo

