CC=gcc

P01=simpleread


EXECS= \
   $(P01) \


EXTRA= \
   dummy \


all:	seealso $(EXECS) 

.phony: clean all seealso

clean: seealso
	rm -f ${EXECS} ${EXTRA}

seealso:
	@echo "=============================="
	@echo "See also file Checklist02a.pdf"
	@echo "=============================="



