


P01=simple_read
P02=exercise1



EXECS= \
       $(P01) \
	   $(P02) \
	   

all:	seealso $(EXECS)

.phony: clean all seealso

clean: seealso
	rm -f ${EXECS}


seealso:
	@echo "======================="
	@echo "yeet"
	@echo "======================="
