


P00=simple_read
P01=exercise1



EXECS= \
       $(P00) \
	   $(P01) \
	   

all:	seealso $(EXECS)

.phony: clean all seealso

clean: seealso
	rm -f ${EXECS}


seealso:
	@echo "======================="
	@echo "yeet"
	@echo "======================="
