
install:
	cp autopush.sh /usr/local/bin/autopush
	chmod +x /usr/local/bin/autopush
	cp maintaingit.sh /usr/local/bin/maintaingit
	chmod +x /usr/local/bin/maintaingit
	cp updatesystem.sh /usr/local/bin/updatesystem
	chmod +x /usr/local/bin/updatesystem

uninstall:
	rm -rf /usr/local/bin/autopush
	rm -rf /usr/local/bin/maintaingit
	rm -rf /usr/local/bin/updatesystem
