# REV01 Wed Sep 11 13:00:05 WIB 2019
# START Wed Sep 11 12:20:16 WIB 2019
#
# To Compile: make
# To Clean:   make clean

CC=gcc

P00=simple_read
P01=simple_writeX
P02=tmp.txt
P03=tmp2.txt
P04=tmp3.txt
P05=total.txt
P06=sering.txt
P07=unik.txt
P08=laporan.txt

EXECS= \
   $(P00) \
   $(P01) \

FILES=\
   $(P02)\
   $(P03)\
   $(P04)\
   $(P05)\
   $(P06)\
   $(P07)\
   $(P08)\

all:	seealso $(EXECS) 
:wQ
.phony: clean all seealso

clean: seealso
	rm -f ${EXECS} ${FILES}
seealso:
	@echo "=============================="
	@echo "ALOOOOOOOOOOOOOOOOOOOOOOOOOOOO"
	@echo "=============================="


