install:
	sudo cp update-upgrade.sh /usr/local/bin/update-upgrade 
	sudo chmod +x /usr/local/bin/update-upgrade 
	sudo cp git-flush.sh /usr/local/bin/git-flush 
	sudo chmod +x /usr/local/bin/git-flush
	sudo cp git-maintain.sh /usr/local/bin/git-maintain
	sudo chmod +x /usr/local/bin/git-maintain

uninstall:
	sudo rm -f /usr/local/bin/update-upgrade /usr/local/bin/git-flush /usr/local/bin/git-maintain

