


P00=simple_read
P01=simple_writeX

EXECS= \
		$(P00) \
		$(P01) \
		# $(P02) \


all:	seealso $(EXECS)

.phony: clean all seealso

clean: seealso
	rm -f ${EXECS}


seealso:
	@echo "======================="
	@echo "         YEET          "
	@echo "======================="
