


P00=simple_read
P01=simple_writeX

EXECS= \
		$(P00) \
		$(P01) \


all:	seealso $(EXECS)

.phony: clean all seealso

clean: seealso
	@rm -f ${EXECS}
	@rm -f tmp.txt
	@rm -f tmp2.txt
	@rm -f tmp3.txt
	@rm -f total.txt
	@rm -f unik.txt
	@rm -f laporan.txt
	@rm -f sering.txt


seealso:
	@echo "======================="
	@echo "         YEET          "
	@echo "======================="
