


P00=simple_read
P01=simple_writeX
P02=exercise1
P03=exercise2
P04=exercise3
P05=exercise4

EXECS= \
		$(P00) \
		$(P01) \
		$(P02) \
		$(P03) \
		$(P04) \
		$(P05) \


all:	seealso $(EXECS)

.phony: clean all seealso

clean: seealso
	rm -f ${EXECS}


seealso:
	@echo "======================="
	@echo "         YEET          "
	@echo "======================="
