CC=gcc

P01=prog0
P03=try1
P04=try2


EXECS= \
   $(P01) \
   $(P03) \
   $(P04) \


all:	seealso $(EXECS) 

.phony: clean all seealso

clean: seealso
	rm -f ${EXECS}

seealso:
	@echo "=============================="
	@echo "See also file Checklist02a.pdf"
	@echo "=============================="